Started invoking local workflows, and changed logic to start using image digest instead of commit hash

diff --git a/.github/workflows/backwards_compatibility_marqo_orchestrator.yml b/.github/workflows/backwards_compatibility_marqo_orchestrator.yml
--- a/.github/workflows/backwards_compatibility_marqo_orchestrator.yml
+++ b/.github/workflows/backwards_compatibility_marqo_orchestrator.yml
@@ -25,17 +25,25 @@ env:
 
 jobs:
   check-if-image-exists:
-    # Responsible for invoking build_push_img.yml GitHub actions workflow in the same repo
-    # that builds a marqo commit using the latest commit and uploads it to a private ECR Registry.
-    # More in /marqo/.github/workflows/build_push_img.yml
+    # Responsible for deciding if we should invoke build_push_img.yml GitHub actions workflow in the same repo.
+    # We do not want to build and push the image if it already exists in the ECR registry, which will be the case if this is a manual developer initiated re-run using the same commit.
     name: Check if image already exists in ECR
     runs-on: ubuntu-latest
     environment: marqo-test-suite
+    outputs:
+      image_exists: ${{ steps.check-image.outputs.image_exists }}
     steps:
       - name: Checkout marqo repo
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
+
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.ECR_PUSHER_AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.ECR_PUSHER_AWS_SECRET_ACCESS_KEY }}
+          aws-region: us-east-1
 
       # step to check for image existence - it uses aws cli to check if the image exists in the ECR registry "marqo-compatibility-tests"
       - name: check for image existence
@@ -44,15 +52,19 @@ jobs:
           echo "Checking for image existence"
           if aws ecr describe-images --repository-name marqo-compatibility-tests --image-ids imageTag=${{ github.sha }}; then
             echo "::set-output name=image_exists::true"
+            echo "Image already exists in ECR"
           else
             echo "::set-output name=image_exists::false"
+            echo "Image doesn't exist" 
           fi
 
   build-and-push-image:
+    # Job to actually build and push image to ECR registry. This job is only triggered if the image does not already exist in the ECR registry.
     name: Build and Push Image
     needs: check-if-image-exists
     if: needs.check-if-image-exists.outputs.image_exists == 'false'
     uses: ./.github/workflows/build_push_img.yml
+    secrets: inherit
     with:
       marqo_ref: "${{ github.sha }}"
       push_to: "ECR"
@@ -61,11 +73,14 @@ jobs:
 
 
   orchestrate:
-    # Job to orchestrate backwards compatibility test execution
+    # Job to orchestrate backwards compatibility test execution. Majorly responsible for determining to_version and for generating the list of for_version to test against.
     name: Orchestrate backwards compatibility test execution
     runs-on: ubuntu-latest
     needs: build-and-push-image
-
+    outputs:
+      list: ${{ steps.generate-versions.outputs.list }}
+      to_version: ${{ steps.get-to-version.outputs.to_version }}
+      image_digest: ${{ steps.image-digest.outputs.digest }}
     environment: marqo-test-suite
     steps:
       # Step to check out the Marqo repository
@@ -88,36 +103,74 @@ jobs:
 
       # Step to determine the target version
       - name: Determine to_version
-        if: $${{ github.event_name != 'workflow_dispatch' && !github.event.inputs.to_version }} # If this condition is met it signifies
-        # that the run was triggered due to mainline push and was not manual. In that case we need to calculate to_version below. This is skipped otherwise.
-        id: get-version
+        id: get-to-version
         run: |
-          VERSION=$(python tests/backwards_compatibility_tests/scripts/determine_to_version.py ${{ github.sha }})
+          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ -n "${{ github.event.inputs.to_version }}" ]; then
+            VERSION="${{ github.event.inputs.to_version }}"
+          else
+            VERSION=$(python tests/backwards_compatibility_tests/scripts/determine_to_version.py ${{ github.sha }})
+          fi
           echo "::set-output name=to_version::$VERSION"
 
       # Step to generate the list of versions to test
       - name: Generate version list #this code block just generates the from_version list and stores it in a versions variable as a list
-        id: versions
+        id: generate-versions
         run: |
           # Run the Python script and capture its output
-          VERSION_LIST=$(python tests/backwards_compatibility_tests/scripts/generate_versions.py ${{ steps.get-version.outputs.to_version }} ${{ env.MAX_VERSIONS_TO_TEST }})
+          VERSION_LIST=$(python tests/backwards_compatibility_tests/scripts/generate_versions.py ${{ steps.get-to-version.outputs.to_version }} ${{ env.MAX_VERSIONS_TO_TEST }})
           echo "::set-output name=list::$VERSION_LIST" 
 
       # Step to display the versions to test
       - name: display versions
         run: |
-          echo "Versions to test: ${{ steps.versions.outputs.list }} against to_version: ${{ steps.get-version.outputs.to_version }}"
+          echo "Versions to test: ${{ steps.generate-versions.outputs.list }} against to_version: ${{ steps.get-to-version.outputs.to_version }}"
 
-  # Job to trigger execution workflows for each version combination
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.ECR_PUSHER_AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.ECR_PUSHER_AWS_SECRET_ACCESS_KEY }}
+          aws-region: us-east-1
+
+      - name: Retrieve image digest
+        id: image-digest
+        run: |
+          echo "Fetching image digest from ECR"
+
+          REPO_NAME="marqo-compatibility-tests"
+          IMAGE_TAG="${{ github.sha }}"
+
+          # Get the image digest
+          echo "Attempting to retrieve image digest for the specific tag: ${{ github.sha }}"
+          DIGEST=$(aws ecr describe-images \
+            --repository-name "$REPO_NAME" \
+            --image-ids imageTag="$IMAGE_TAG" \
+            --query 'imageDetails[0].imageDigest' \
+            --output text) || true
+
+          echo "DIGEST result: $DIGEST"
+          if [ "$DIGEST" == "None" ] || [ -z "$DIGEST" ]; then
+            echo "Image not found in ECR or command failed."
+            exit 1
+          fi
+          
+          echo "Successfully retrieved image Image Digest: $DIGEST"
+
+          # Set the digest as a global environment variable
+          echo "::set-output name=digest::$DIGEST"
+
+
   run-execution-workflow:
+    # Job to trigger execution workflows for each version combination
     name: Run all execution workflows
     needs: orchestrate
     strategy:
       matrix:
         from_version: ${{ fromJson(needs.orchestrate.outputs.list) }}
     uses: ./.github/workflows/backwards_compatibility_marqo_execution.yml
+    secrets: inherit
     with:
       from_version: ${{ matrix.from_version }}
       to_version: ${{ needs.orchestrate.outputs.to_version }}
-      to_version_tag: ${{ github.sha }}
+      to_version_digest: ${{ needs.orchestrate.outputs.image_digest }} # Pass the image digest to the execution workflow
       to_image: ${{ github.event.inputs.to_image || '' }}
