Add coverage check to integ tests

diff --git a/.github/workflows/integration_tests_CI.yml b/.github/workflows/integration_tests_CI.yml
--- a/.github/workflows/integration_tests_CI.yml
+++ b/.github/workflows/integration_tests_CI.yml
@@ -277,7 +277,29 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: merged-coverage
-          path: marqo/htmlcov/
+          path: |
+            marqo/htmlcov/
+            marqo/diff_cov.html
+
+      - name: Test and coverage report summary
+        continue-on-error: true
+        run: |
+          echo "# Test Summary" >> $GITHUB_STEP_SUMMARY
+          cat marqo/pytest_result_summary.md >> $GITHUB_STEP_SUMMARY
+
+          echo "# Coverage Summary, Slow Tests and Failed Tests" >> $GITHUB_STEP_SUMMARY
+          echo '```text' >> $GITHUB_STEP_SUMMARY
+          awk '/---------- coverage:/ {flag=1} flag' marqo/pytest_output.txt >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+
+          cat marqo/diff_cov.md >> $GITHUB_STEP_SUMMARY
+
+      - name: Fail Job If Tests or Coverage Failed
+        if: ${{ steps.run_unit_tests.outcome == 'failure' || steps.check_test_coverage.outcome == 'failure' }}
+        run: |
+          echo "Tests or coverage checks failed. Marking job as failed."
+          exit 1
+        shell: bash
 
   Stop-Runner:
     needs:
