Update large model tests after merge

diff --git a/.github/workflows/largemodel_integration_tests_CI.yml b/.github/workflows/largemodel_integration_tests_CI.yml
--- a/.github/workflows/largemodel_integration_tests_CI.yml
+++ b/.github/workflows/largemodel_integration_tests_CI.yml
@@ -140,6 +140,8 @@ jobs:
         run: python marqo/scripts/vespa_local/vespa_local.py full-start --Shards ${{ inputs.number_of_shards || 1 }} --Replicas ${{ inputs.number_of_replicas || 0 }}
 
       - name: Run Large Model Integration Tests (Part ${{ matrix.part }})
+        id: run_tests
+        continue-on-error: true
         run: |
           # Define these for use by Marqo
           export VESPA_CONFIG_URL=http://localhost:19071
@@ -155,8 +157,61 @@ jobs:
           
           export PYTHONPATH="./marqo/tests/integ_tests:./marqo/src"
 
-          # Run only the assigned test partition
-          pytest marqo/tests/integ_tests --largemodel --split-n 4 --split-part ${{ matrix.part }} --suppress-skips
+          cd marqo
+          export PYTHONPATH="./tests/integ_tests:./src"
+          set -o pipefail
+          pytest --largemodel \
+            --durations=100 --cov=src --cov-branch --cov-context=test \
+            --cov-report=html:cov_html --cov-report=xml:cov.xml --cov-report term:skip-covered \
+            --md-report --md-report-flavor gfm --md-report-output pytest_result_summary.md \
+            --split-n 4 --split-part ${{ matrix.part }} --suppress-skips \
+            tests/integ_tests | tee pytest_output.txt
+
+      - name: Check Test Coverage of New Code
+        id: check_test_coverage
+        continue-on-error: true
+        run: |
+          if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
+            export BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
+            cd marqo
+            echo "Running diff-cover against branch $BASE_BRANCH"
+            git fetch origin $BASE_BRANCH:$BASE_BRANCH
+            diff-cover cov.xml --html-report diff_cov.html --markdown-report diff_cov.md \
+              --compare-branch $BASE_BRANCH
+          else
+            echo "Skipping diff-cover on Push events"
+            echo "Skipped diff-cover on Push events" > marqo/diff_cov.md
+            touch marqo/diff_cov.html
+          fi
+
+      - name: Upload Test Report
+        uses: actions/upload-artifact@v4
+        continue-on-error: true
+        with:
+          name: marqo-test-report
+          path: |
+            marqo/cov_html/
+            marqo/diff_cov.html
+
+      - name: Test and coverage report summary
+        continue-on-error: true
+        run: |
+          echo "# Test Summary" >> $GITHUB_STEP_SUMMARY
+          cat marqo/pytest_result_summary.md >> $GITHUB_STEP_SUMMARY
+          
+          echo "# Coverage Summary, Slow Tests and Failed Tests" >> $GITHUB_STEP_SUMMARY
+          echo '```text' >> $GITHUB_STEP_SUMMARY
+          awk '/---------- coverage:/ {flag=1} flag' marqo/pytest_output.txt >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          
+          cat marqo/diff_cov.md >> $GITHUB_STEP_SUMMARY
+
+      - name: Fail Job If Tests or Coverage Failed
+        if: ${{ steps.run_tests.outcome == 'failure' || steps.check_test_coverage.outcome == 'failure' }}
+        run: |
+          echo "Tests or coverage checks failed. Marking job as failed."
+          exit 1
+        shell: bash
 
   Stop-Runner:
     needs:
@@ -165,7 +220,7 @@ jobs:
     if: ${{ always() }} # Ensures the runner is stopped even if tests fail
     strategy:
       matrix:
-        instance: [0, 1, 2, 3]  # Zero-based index for JSON list access
+        instance: [ 0, 1, 2, 3 ]  # Zero-based index for JSON list access
     uses: ./.github/workflows/stop_ec2_runner.yml
     with:
       label: ${{ fromJSON(needs.Create-Matrix.outputs.labels)[matrix.instance] }}
