Add `Report-required-test-status` in Github Workflows and add missed release notes (#1200)

diff --git a/.github/workflows/run_required_checks.yml b/.github/workflows/run_required_checks.yml
--- a/.github/workflows/run_required_checks.yml
+++ b/.github/workflows/run_required_checks.yml
@@ -64,4 +64,19 @@ jobs:
       number_of_replicas: 0
     secrets: inherit
 
-  # TODO: Add more jobs here as needed
+  # GitHub status will rely on the result of this step to determine if the PR is ready for merge
+  Report-required-test-status:
+    needs: [Determine-changes, Run-integration-tests]
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+      - name: Set integration test status
+        run: |
+          if [[ "${{ needs.Determine-changes.outputs.non_documentation_changes_found }}" == "false" ]]; then
+            echo "Integration tests skipped due to markdown-only changes."
+          elif [[ "${{ needs.Run-integration-tests.result }}" == "success" ]]; then
+            echo "Integration tests completed successfully."
+          else
+            echo "Integration tests failed or did not run."
+            exit 1
+          fi
