output more in the summary

diff --git a/.github/workflows/unit_test_200gb_CI.yml b/.github/workflows/unit_test_200gb_CI.yml
--- a/.github/workflows/unit_test_200gb_CI.yml
+++ b/.github/workflows/unit_test_200gb_CI.yml
@@ -169,6 +169,7 @@ jobs:
 
           cd marqo
           export PYTHONPATH="./tests:./src:."
+          set -e
           pytest --ignore=tests/test_documentation.py --ignore=tests/backwards_compatibility_tests --durations=100 --cov=src --cov-branch --cov-context=test \
             --cov-report=html:cov_html --cov-report=xml:cov.xml --cov-report term:skip-covered --cov-fail-under=35 \
             --md-report --md-report-flavor gfm --md-report-exclude-outcomes passed xpassed \
@@ -203,7 +204,12 @@ jobs:
       - name: Test and coverage report summary
         continue-on-error: true
         run: |
+          echo "# Test Summary" >> $GITHUB_STEP_SUMMARY
           cat marqo/pytest_result_summary.md >> $GITHUB_STEP_SUMMARY
+          echo "# Coverage Summary, Slow Tests and Failed Tests" >> $GITHUB_STEP_SUMMARY
+          echo "```text" >> $GITHUB_STEP_SUMMARY
+          awk '/---------- coverage:/ {flag=1} flag' pytest_output.txt >> $GITHUB_STEP_SUMMARY
+          echo "```" >> $GITHUB_STEP_SUMMARY
           cat marqo/diff_cov.md >> $GITHUB_STEP_SUMMARY
 
       - name: Fail Job If Tests or Coverage Failed
