fix indent

diff --git a/.github/workflows/unit_test_200gb_CI.yml b/.github/workflows/unit_test_200gb_CI.yml
--- a/.github/workflows/unit_test_200gb_CI.yml
+++ b/.github/workflows/unit_test_200gb_CI.yml
@@ -76,22 +76,22 @@ jobs:
 
       - name: Start Vespa
         run: |
-            retry_command() {
-              local n=1
-              local max=5
-              local delay=5
-              while true; do
-                  "$@" && break || {
-                      if [[ $n -lt $max ]]; then
-                          ((n++))
-                          echo "Command failed. Attempt $n/$max:"
-                          sleep $delay;
-                      else
-                          echo "The command has failed after $n attempts."
-                          return 1
-                      fi
-                  }
-              done
+          retry_command() {
+            local n=1
+            local max=5
+            local delay=5
+            while true; do
+                "$@" && break || {
+                    if [[ $n -lt $max ]]; then
+                        ((n++))
+                        echo "Command failed. Attempt $n/$max:"
+                        sleep $delay;
+                    else
+                        echo "The command has failed after $n attempts."
+                        return 1
+                    fi
+                }
+            done
           }
           
           echo "Updating package list"
